### ISSUE TITLE
issue with parsing test data

### ISSUE THREAD

**Issue by garyjellyarms** [firefly-cpp/sport-activities-features#104]
an issue while trying to perform the Hills.identify_hills(), pictures of the stack call back and some of the test files that caused the issue
![errors](https://user-images.githubusercontent.com/79595804/196718834-6cea0319-9da8-4e42-a3c7-52c749d38c8c.png)
![wrong_files](https://user-images.githubusercontent.com/79595804/196718844-28a3766c-c627-4305-9f93-042e4d0f6ea3.png)

**Comment by firefly-cpp** [comment]
@garyjellyarms, any progress regarding this issue? Can we close this issue now?

**Comment by firefly-cpp** [comment]
@garyjellyarms, any progress regarding this issue? Can we close this issue now?

**Comment by firefly-cpp** [comment]
@alenrajsp, can you please verify the solution?
