### ISSUE TITLE
Function Intervals.identify_intervals() Error

### ISSUE THREAD

**Issue by Mtvrt123** [firefly-cpp/sport-activities-features#106]
Intervals.identify_intervals()

Error:  float division by zero
![error](https://user-images.githubusercontent.com/50879568/199532618-d03ef729-9ef7-4b99-8ab4-a2ef75e5aab5.jpg)

**Comment by firefly-cpp** [comment]
@luckyLukac

**Comment by firefly-cpp** [comment]
@Mtvrt123, if I remember correctly, some fixes were proposed to avoid this issue. Do you still encounter similar problems? If there is a chance, please prepare corrections.

**Comment by firefly-cpp** [comment]
@luckyLukac, can you also take a look at this issue? Since this is your implementation, you may easily apply a patch.

**Comment by firefly-cpp** [comment]
@KukovecRok, if you have a time...
