### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/sport-activities-features#144]
COMMAND: poetry build 

RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/lib/python3.11/site-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]

**Comment by firefly-cpp** [comment]
@KukovecRok

**Comment by KukovecRok** [comment]
@firefly-cpp what is your local poetry version? Probably need to update it

**Comment by firefly-cpp** [comment]
It is indeed working using the recent version from pip.
