### ISSUE TITLE
Add 0.3.13 to pypi

### ISSUE THREAD

**Issue by alenrajsp** [firefly-cpp/sport-activities-features#145]
Please upload the newer version (0.3.13) to pypi, so that it can be used in sport-activities-features-gui (pyproject toml has 0.3.13 specified).

![image](https://github.com/firefly-cpp/sport-activities-features/assets/27721714/a26135bc-8164-4440-86bf-6babc690727a)

**Comment by firefly-cpp** [comment]
try now
