### ISSUE TITLE
Code refactoring for TCX/GPX Manipulation

### ISSUE THREAD

**Issue by MihaMi27** [firefly-cpp/sport-activities-features#199]
# Reasoning
As it is currently implemented, if you need activity data and the integral metrics, a file is read two times which impacts the performance of using the library. With the following refactoring, the data is read only once for each file and held in memory for further use. 
For example, if you wanted to parse a 10 GB folder of .tcx or .gpx files and extract the previously mentioned data, it would need to read the file twice, making it a total of 20 GB read.
## Pros
- improve code reusability
- faster processing speeds
- easier implementation of new functionalities
## Cons
- users would be forced to write more memory-efficient code
- rewrite of unit tests and examples 
- regeneration of the library documentation 

# Refactoring
Classes TCXFile and GPXFile should be refactored in the following ways:
### read_one_file()
Should be split into two functions:
- one for actually reading the data (should keep the same name)
  - input is the file name,
  - output should be an instance of  TCXExercise,
- one for returning activity data
  - input should be an instance of TCXExercise and optionally numpy_array bool, 
  - output can be the same (i.e. activity = { activity_type, altitudes, distances, ... })
### extract_integral_metrics()
Input should be modified to receive an instance of TCXExercise, instead of filename.

### read_one_file()
Should be split into two functions:
- one for actually reading the data (should keep the same name)
  - input is the file name,
  - output should be a list of GPXTrackPoints or a separate class GPXExercise to keep it consistent with it's TCX counterpart.
- one for returning activity data
  - input should be the output of read_one_file() and optionally numpy_array bool,
  - output can be the same (i.e. activity = { activity_type, altitudes, distances, ... }). 
  - Currently it also casts them into TCXTrackPoints (might be a bug). 
### extract_integral_metrics()
Input should be modified to receive the output of read_one_file(), instead of filename.

**Comment by firefly-cpp** [comment]
Good point! We support your idea. Please go ahead and implement the proposed changes, and then we can release a new version of this package.

**Comment by firefly-cpp** [comment]
@all-contributors, please add @MihaMi27 for ideas

**Comment by MihaMi27** [comment]
Implemented and merged. Closing issue.
