### ISSUE TITLE
Installation errors on Windows

### ISSUE THREAD

**Issue by FaricSamo** [firefly-cpp/sport-activities-features#20]
![image](https://user-images.githubusercontent.com/46571030/119045254-7cdfd980-b9bb-11eb-9405-da907f122bfe.png)

**Comment by spelap** [comment]
For Windows 10 and Python v3.7.6, the package installation with the _pip install sport-activities-features_ command has been verified to work correctly.

I suggest installing Anaconda and running the _pip install sport-activities-features_ command in the Anaconda command prompt on your computer.
If it returns an error that some library is not installed or that is not the correct version, install that library of the required version (also with pip install ... or conda install ...) and do the installation again (you can also do uninstall).

**Comment by firefly-cpp** [comment]
Thank you @spelap!

@FaricSamo, please follow to the instructions of @spelap.

If there are any additional problems, please let us know.
