### ISSUE TITLE
Support FIT files

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/sport-activities-features#43]
GPX and TCX file extensions are now supported by this software. However, support for FIT files is still missing. It is heavily used by Garmin as well as Zwift.

[More info](https://developer.garmin.com/fit/file-types/)

Any volunteers for working on this task? @alenrajsp or @luckyLukac?

**Comment by alenrajsp** [comment]
@firefly-cpp can we get some sample FIT files?

**Comment by alenrajsp** [comment]
@firefly-cpp

**Comment by firefly-cpp** [comment]
@alenrajsp, an example of a FIT file is added in commit #119. It is possible to find several open-source implementations of FIT parsers. Still, the most convenient way is to develop a straightforward parser from scratch and then upgrade it from time to time so it can live within this package.

What do you think?
