### ISSUE TITLE
Poetry Issue

### ISSUE THREAD

**Issue by luckyLukac** [firefly-cpp/sport-activities-features#44]
There is an issue with poetry.lock and/or pyproject.toml (the file cannot be read nor updated). A more detailed description can be found in the attached screenshot.

![Screenshot 2021-11-18 174445](https://user-images.githubusercontent.com/73126820/142459197-23609873-9783-49f5-ae15-ddaa88bd53b7.jpg)

**Comment by firefly-cpp** [comment]
Thanks @luckyLukac for info.

I have already checked this issue. Actually, it works for me. New lock file is online. 

Please send me your feedback.

**Comment by luckyLukac** [comment]
@firefly-cpp now it does work for me as well. Thank you very much.

Was there an issue with the TOML file?

**Comment by firefly-cpp** [comment]
Nice to hear that @luckyLukac!

Previous lock file was malformed.

**Comment by luckyLukac** [comment]
Alright. Since the issue is now resolved, this topic can be closed.
