### ISSUE TITLE
Add interruption detection functionality

### ISSUE THREAD

**Issue by alenrajsp** [firefly-cpp/sport-activities-features#48]
From a parsed TCX / GPX file detect interruptions

**Comment by alenrajsp** [comment]
@firefly-cpp Please assign me on this task

**Comment by firefly-cpp** [comment]
Thanks @alenrajsp!

**Comment by firefly-cpp** [comment]
It would be a great addition for this package.

**Comment by alenrajsp** [comment]
Proposed solution avaliable as pull request: https://github.com/firefly-cpp/sport-activities-features/pull/49
