### ISSUE TITLE
'classes' module not finished

### ISSUE THREAD

**Issue by luckyLukac** [firefly-cpp/sport-activities-features#60]
['classes'](https://github.com/firefly-cpp/sport-activities-features/blob/main/sport_activities_features/classes.py) module is under early WIP.

**Comment by alenrajsp** [comment]
I am currently working on improving the StoredSegments (part of _.classes_)

**Comment by firefly-cpp** [comment]
@alenrajsp, any progress regarding this issue? Can we close this issue? I remember some changes are already incorporated in the latest release.
