### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/sport-activities-features#66]
@alenrajsp, your tests are failing. Please check it out!

FAILED sport_activities_features/tests/test_overpy_node_manipulation.py::TestWeather::test_generated_object_altitudes - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

FAILED sport_activities_features/tests/test_overpy_node_manipulation.py::TestWeather::test_generated_object_properties - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by alenrajsp** [comment]
No tests should be failing as of b85c68e660a763ae930bc226ad5c07537d9a21a5 commit.
