### ISSUE TITLE
Error reading GPX file

### ISSUE THREAD

**Issue by TusekEvgen** [firefly-cpp/sport-activities-features#77]
Road : https://www.google.com/maps/dir/46.5408076,15.6852325/46.5418164,15.6877738/46.542007,15.685388/@46.5405891,15.6855908,18z/data=!4m2!4m1!3e2

Copied link : https://goo.gl/maps/utCLQRV2c4VUpcJDA

Used : https://mapstogpx.com/ to get .gpx file

Error occurred when reading downloaded file

![gpxFileReadingError](https://user-images.githubusercontent.com/103990733/163954092-3e062bbc-496b-4bd3-bfda-171b7841d4ab.png)

**Comment by firefly-cpp** [comment]
Thanks for raising this issue. I believe that the main problem is that there is no time data in this gpx. Using conditionals may fix this issue. @alenrajsp please fix this issue.

@TusekEvgen, please also share the entire gpx file.

**Comment by TusekEvgen** [comment]
[mapstogpx20220419_075122.gpx.tar.gz](https://github.com/firefly-cpp/sport-activities-features/files/8515700/mapstogpx20220419_075122.gpx.tar.gz)

**Comment by alenrajsp** [comment]
@firefly-cpp please deploy new version on pypi. Issue fixed in new commit (#78 )

**Comment by firefly-cpp** [comment]
@alenrajsp, done!

@TusekEvgen, please report any further issues!
