### ISSUE TITLE
Read one GPX file produces division by zero

### ISSUE THREAD

**Issue by KoprivcLuka** [firefly-cpp/sport-activities-features#83]
When I mass imported a mass collection, exported from strava, a large ammount of them failed. It would appear, when parsing the file a point is somehow read twice but differently - picture provided bellow. 

![image](https://user-images.githubusercontent.com/45632449/175114381-6c0e6a0d-e0ae-44b6-a7c8-49fc2524e745.png)

![image](https://user-images.githubusercontent.com/45632449/175113701-9c6cbb1a-4a4f-4a4b-8ba4-488a34662054.png)

These different points are actually one the the XML

![image](https://user-images.githubusercontent.com/45632449/175114975-fe64faa4-0739-4dd8-9b2a-a34424b516f6.png)

**Comment by firefly-cpp** [comment]
Thanks @KoprivcLuka for raising this issue.

**Comment by alenrajsp** [comment]
I've checked the code and fixed it so that it still works even if two timestamps were somehow recorded with the same time. 
Pull request #84 should fix this issue #83 !

**Comment by firefly-cpp** [comment]
@KoprivcLuka, please install the latest release.

**Comment by KoprivcLuka** [comment]
The fix works, however i have to warn you, that it appears that used library gpxpy has trouble parsing some files. 

![image](https://user-images.githubusercontent.com/45632449/175365964-0af287e4-9529-456f-b46a-e3246e52d94f.png)

**Comment by alenrajsp** [comment]
@KoprivcLuka can you please upload the troubled GPX files so I can check them out.

**Comment by KoprivcLuka** [comment]
[L_Koprivc_2021_03_23_Brnica.zip](https://github.com/firefly-cpp/sport-activities-features/files/8994348/L_Koprivc_2021_03_23_Brnica.zip)

This is an example of an unparsable file which produces above error.

**Comment by KoprivcLuka** [comment]
[BrokenFiles.zip](https://github.com/firefly-cpp/sport-activities-features/files/8995309/BrokenFiles.zip)
I have found several more files which should be valid XML, exported from https://www.gpsvisualizer.com that seem to cause issues

**Comment by firefly-cpp** [comment]
@KoprivcLuka, @alenrajsp,  any progress regarding this issue?

**Comment by alenrajsp** [comment]
#120 PR should work with "https://l_koprivc_2021_03_23_brnica.zip/".

**Comment by alenrajsp** [comment]
PR #121 adds tests for UTF-8 formatting fixed in PR #120. The tests are passing and will no longer happen in the future so this issue can be closed.
